config/routes.rb
Rails.application.routes.draw do
  root to: "tops#index"
  resources :tops, only: [:index]
  
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  devise_scope :user do
    get 'users/registrations/new',      to: 'users/registrations#new'
    get 'users/registrations/index',      to: 'users/registrations#index'
    get 'users/registrations/mail_check', to: 'users/registrations#mail_check'
    get 'users/registrations/completed',  to: 'users/registrations#completed'
  end
  
  resources :skills, only: [:show]
  
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user

  PREFECTURE_NAMES= [
    '北海道','青森県','岩手県','宮城県','秋田県','山形県','福島県',
    '茨城県','栃木県','群馬県','埼玉県','千葉県','東京都','神奈川県',
    '新潟県','富山県','石川県','福井県','山梨県','長野県','岐阜県',
    '静岡県','愛知県','三重県','滋賀県','京都府','大阪府','兵庫県',
    '奈良県','和歌山県','鳥取県','島根県','岡山県','広島県','山口県',
    '徳島県','香川県','愛媛県','高知県','福岡県','佐賀県','長崎県',
    '熊本県', '大分県','宮崎県','鹿児島県','沖縄県'
  ]

  validates :postal_code, :prefecture_name, :city, :street, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
  
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :skills
  has_ancestry
    
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :skill
  
end

app/models/scraping.rb
require 'mechanize'

class Scraping < ApplicationRecord
  def self.scrape
    agent = Mechanize.new
    page = agent.get("https://coconala.com/")
    elements = page.search("div.subCategoryBoxInner")
    elements.each do |element|
      # puts element.inner_text
      category = Category.new
      category.name = element.inner_text
      category.save
    end
  end
end

app/models/skill.rb
class Skill < ApplicationRecord
  belongs_to :saler, class_name: 'User'
  belongs_to :buyer, class_name: 'User'
  has_many :favorites, dependent: :destroy
  has_many :users, through: :favorites
  belongs_to :category
  has_many :skill_images, dependent: :destroy
  accepts_nested_attributes_for :skill_images, allow_destroy: true

  validates_associated :skill_images

end

app/models/skill_image.rb
class SkillImage < ApplicationRecord
  belongs_to :skill, optinal: true
  mount_uploader :image, ImageUploader

end

app/models/user.rb
class User < ApplicationRecord
  has_many :skills 
  has_many :favirites, dependent: :destroy
  has_one :card 
  has_one :address
  has_many :bought_skills, foreign_key: 'buyer_id', class_name: 'Skill'
  has_many :saling_skills,  ->{where("buyer_id is NULL")},foreign_key: 'saler_id', class_name: 'Skill'
  has_many :sold_skills, ->{where("buyer_id is not NULL")}, foreign_key: 'saler_id', class_name: 'Skill'
  has_many :user_award
  has_many :user_career
  has_many :user_estimated_amount
  has_many :user_speciality
  has_many :user_portfolio
  
  devise  :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  validates :email,     format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i}
  validates :nickname,  uniqueness: true ,length: { in: 3..20 }, uniqueness: true, presence: true
  validates :password,  format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]{6,128}/}, length: { in: 6..20 },  presence: true
  validates :birthday,  presence: true
  validates :gender,    presence: true

end

app/models/user_award.rb
class UserAward < ApplicationRecord
  belongs_to :user
  

end

app/models/user_career.rb
class UserCareer < ApplicationRecord
  belongs_to :user

end

app/models/user_image.rb
class UserImage < ApplicationRecord
  belongs_to :user, optional: true
  mount_uploader :image, ImageUploader
end

app/models/user_portfolio.rb
class UserPortfolio < ApplicationRecord
  belongs_to :user
end

app/models/user_speciality.rb
class UserSpeciality < ApplicationRecord
  belongs_to :user
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def index
    @category_parent = Category.where(ancestry: nil)

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/form_helper.rb
module FormHelper                                                           
  class FormWithErrorMessageBuilder < ActionView::Helpers::FormBuilder
    # 従来のフォームに加えて、エラーがある場合にエラーメッセージを表示するメソッド
    def input_field_with_error(attribute, options={}, &block)   
      # 入力フォームと同じ属性のエラーメッセージを取得する                
      error_messages = @object.errors.full_messages_for(attribute) 
      # エラーがある場合のみ、エラー用のHTMLにする             
      if error_messages.any?                                                    
        options[:class] = "error-class"              
        error_contents = create_error_div(attribute, error_messages)            
      end
      # 従来の入力フォーム と 生成されたエラーメッセージ を連結して返す  
      block.call + error_contents    
    end                                                                                                                             
    # エラーメッセージのHTMLタグを作成する
    def create_error_div(attribute, messages)    
      # content_tag でHTMLタグを生成                               
      @template.content_tag(:div, class: "error-class") do
        messages.each do|message|                                              
          @template.concat(@template.content_tag(:div, message))                
        end                   
      end          
    end

    # 既存のビューヘルパーメソッドをオーバーライドする
    def text_field(attribute, options={})                                       
      input_field_with_error(attribute, options) do                             
        super                                                     
      end                                                          
    end  
    # email_fieldにエラー分を適用
    def email_field(attribute, options={})                                      
      input_field_with_error(attribute, options) do                             
        super                            
      end        
    end 
    # password_fieldにエラー分を適用
    def password_field(attribute, options={} )                                   
      input_field_with_error(attribute, options) do                             
        super    
      end       
    end 
    # date_selectにエラー分を適用
    def date_select(attribute, options={} )                                   
      input_field_with_error(attribute, options) do                             
        super    
      end       
    end 
    # select_buttonにエラー分を適用
    def select_button(attribute, options={} )                                   
      input_field_with_error(attribute, options) do                             
        super    
      end       
    end 
  end                                                                
end                           

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.haml
.footer
  .footer__main
    .column1
      .column1__title
        サービスを見つける
      %ul.column1__lists
        %li.list
          = link_to "#", class: "list__link" do
            カテゴリ一覧
        %li.list
          = link_to "#", class: "list__link" do
            公開依頼（旧リクエストボード）
        %li.list
          = link_to "#", class: "list__link" do
            ココナラ法律相談
        %li.list
          = link_to "#", class: "list__link" do
            ココナラマガジン
      .column1__title
        ご利用ガイド
      %ul.column1__lists
        %li.list
          = link_to "#", class: "list__link" do
            ご利用ガイド
        %li.list
          = link_to "#", class: "list__link" do
            サービスを出品したい
        %li.list
          = link_to "#", class: "list__link" do
            サービスを購入したい
        %li.list
          = link_to "#", class: "list__link" do
            安心・安全の取り組み
        %li.list
          = link_to "#", class: "list__link" do
            お支払い方法・手数料
        %li.list
          = link_to "#", class: "list__link" do
            取引の流れ
        %li.list
          = link_to "#", class: "list__link" do
            ルールとマナー
        %li.list
          = link_to "#", class: "list__link" do
            評価について
        %li.list
          = link_to "#", class: "list__link" do
            電話相談サービスについて
        %li.list
          = link_to "#", class: "list__link" do
            ビデオチャットについて
        %li.list
          = link_to "#", class: "list__link" do
            公開依頼(旧リクエストボード)
        %li.list
          = link_to "#", class: "list__link" do
            法人アカウントについて
    .column2
      .column2__title
        サービスを出品する
      %ul
        %li.list
          = link_to "#", class: "list__link" do
            出品する
        %li.list
          = link_to "#", class: "list__link" do
            出品のコツ
        %li.list
          = link_to "#", class: "list__link" do
            サービス価格・有料オプション
        %li.list
          = link_to "#", class: "list__link" do
            ランク制度について
        %li.list
          = link_to "#", class: "list__link" do
            PRO認定について
        %li.list
          = link_to "#", class: "list__link" do
            出品者インタビュー
        %li.list
          = link_to "#", class: "list__link" do
            ココナラクラブオフ
      %ul
      .column2__title
        サイト情報
      %ul
        %li.list
          = link_to "#", class: "list__link" do
            ココナラ利用規約
        %li.list
          = link_to "#", class: "list__link" do
            加盟店規約
        %li.list
          = link_to "#", class: "list__link" do
            有償ポイントに関する特約
        %li.list
          = link_to "#", class: "list__link" do
            資金決済法に基づく表記
        %li.list
          = link_to "#", class: "list__link" do
            特定商取引法に基づく表記
        %li.list
          = link_to "#", class: "list__link" do
            運営会社
        %li.list
          = link_to "#", class: "list__link" do
            採用情報
        %li.list
          = link_to "#", class: "list__link" do
            プライバシーポリシー
        %li.list
          = link_to "#", class: "list__link" do
            よくある質問
        %li.list
          = link_to "#", class: "list__link" do
            お問い合わせ
        %li.list
          = link_to "#", class: "list__link" do
            招待コード
        %li.list
          = link_to "#", class: "list__link" do
            評判・口コミ・感想
    .column3
      .column3__title
        ココナラをもっと知る
      %ul
        %li.list
          = link_to "#", class: "list__link" do
            ココナラとは
        %li.list
          = link_to "#", class: "list__link" do
            Twitter
        %li.list
          = link_to "#", class: "list__link" do
            Facebook
        %li.list
          = link_to "#", class: "list__link" do
            ブログ
        %li.list
          = link_to "#", class: "list__link" do
            ココナラ活用マガジン
    .feedback
      .inquiry-box
        .inquiry-box__title
          ココナラへのご意見・ご要望を
          %br
          お聞かせください
        .inquiry-box__form
          = form_tag('/', method: :post, class: "box") do
            %textarea.box__text{:cols => "30", :name => "text", :placeholder => "サービスへのご意見、ご要望をお聞かせください。ご意見・ご要望に返信できないことをあらかじめご了承ください。", :rows => "2"}
            %input.box__button{:type => "submit", :value => "送信する"}/

app/views/layouts/_header.html.haml
.header
  .header__main
    .header__main__inner
      -# =image_tag "skill_share_logo.png",class:"skill-logo", size:"30%"
      %ul.dropdwn
        %li
          サービスを探す
          %ul.dropdwn_menu
            %li
              %a{:href => "#"} プログラマー
            %li
              %a{:href => "#"} デザイナー
        %li
          出品者を探す
          %ul.dropdwn_menu
            %li
              %a{:href => "#"} B1
            %li
              %a{:href => "#"} B2
            %li
              %a{:href => "#"} B3
        %li
          公開依頼する
                    
          %ul.dropdwn_menu
            %li
              %a{:href => "#"} C1
            %li
              %a{:href => "#"} C2
            %li
              %a{:href => "#"} C3
            %li
              %a{:href => "#"} C4
        %li
          ブログを探す
          %ul.dropdwn_menu
            %li
              %a{:href => "#"} D1
            %li
              %a{:href => "#"} D2
            %li
              %a{:href => "#"} D3
            %li
              %a{:href => "#"} D4
            %li
              %a{:href => "#"} D5
        %li
          仕事を探す
          %ul.dropdwn_menu
            %li
              %a{:href => "#"} D1
            %li
              %a{:href => "#"} D2
            %li
              %a{:href => "#"} D3
            %li
              %a{:href => "#"} D4
            %li
              %a{:href => "#"} D5


    -#   =link_to root_path do
    -#     = image_tag "skill_share_logo.png", class: "header-main-logo"
    -#   .header__main__inner__search
    -#     .header__main__inner__search__form
    -#       = form_for "#" do |f| 
    -#         .input-box
    -#           = f.text_field :keyword, class: "header__main__inner__search__txt", placeholder:"キーワードから探す"
    -#           %label.header__main__inner__search__btn
    -#             = icon('fas', 'search', class: '')
    -#             = f.submit "", class: "header__main__inner__search__btn--display"

        
  -#     .header__main__inner__nav__right
  -#       %ul.box
  -#         -if user_signed_in?
  -#           %li.user_box__nav__right__new
  -#             =link_to "スキル提供", "#" 
  -#           %li.user_box__nav__right__mypage
  -#             =link_to "マイページ", "#"
  -#           %li.user_box__nav__right__logout
  -#             =link_to "ログアウト", destroy_user_session_path, :method => :delete

  -#         -else
  -#           %li.user_box__nav__right__new
  -#             =link_to "新規登録", users_registrations_index_path
  -#           %li.head__in__nav__right__login
  -#             =link_to "ログイン", new_user_session_path

  
  -# .header_sub
  -#   .header_sub__inner
  -#     %ul.dropdwn
  -#       %li
  -#         イラスト・似顔絵・漫画
  -#         %ul.dropdwn_menu
  -#           %li
  -#             %a{:href => "#"} プログラマー
  -#           %li
  -#             %a{:href => "#"} デザイナー
  -#       %li
  -#         デザイン
  -#         %ul.dropdwn_menu
  -#           %li
  -#             %a{:href => "#"} B1
  -#           %li
  -#             %a{:href => "#"} B2
  -#           %li
  -#             %a{:href => "#"} B3
  -#       %li
  -#         Webサイト制作・デザイン
                    
  -#         %ul.dropdwn_menu
  -#           %li
  -#             %a{:href => "#"} C1
  -#           %li
  -#             %a{:href => "#"} C2
  -#           %li
  -#             %a{:href => "#"} C3
  -#           %li
  -#             %a{:href => "#"} C4
  -#       %li
  -#         音楽・ナレーション
  -#         %ul.dropdwn_menu
  -#           %li
  -#             %a{:href => "#"} D1
  -#           %li
  -#             %a{:href => "#"} D2
  -#           %li
  -#             %a{:href => "#"} D3
  -#           %li
  -#             %a{:href => "#"} D4
  -#           %li
  -#             %a{:href => "#"} D5

  -#       %li
  -#         動画・写真・画像
  -#         %ul.dropdwn_menu
  -#           %li
  -#             %a{:href => "#"} D1
  -#           %li
  -#             %a{:href => "#"} D2
  -#           %li
  -#             %a{:href => "#"} D3
  -#           %li
  -#             %a{:href => "#"} D4
  -#           %li
  -#             %a{:href => "#"} D5

  -#       %li
  -#         IT・プログラミング
  -#         %ul.dropdwn_menu
  -#           %li
  -#             %a{:href => "#"} D1
  -#           %li
  -#             %a{:href => "#"} D2
  -#           %li
  -#             %a{:href => "#"} D3
  -#           %li
  -#             %a{:href => "#"} D4
  -#           %li
  -#             %a{:href => "#"} D5

  -#       %li
  -#         集客・Webマーケティング
  -#         %ul.dropdwn_menu
  -#           %li
  -#             %a{:href => "#"} D1
  -#           %li
  -#             %a{:href => "#"} D2
  -#           %li
  -#             %a{:href => "#"} D3
  -#           %li
  -#             %a{:href => "#"} D4
  -#           %li
  -#             %a{:href => "#"} D5

  -#       -# %li
  -#       -#   翻訳・語学
  -#       -#   %ul.dropdwn_menu
  -#       -#     %li
  -#       -#       %a{:href => "#"} D1
  -#       -#     %li
  -#       -#       %a{:href => "#"} D2
  -#       -#     %li
  -#       -#       %a{:href => "#"} D3
  -#       -#     %li
  -#       -#       %a{:href => "#"} D4
  -#       -#     %li
  -#       -#       %a{:href => "#"} D5

  -#       -# %li
  -#       -#   悩み相談・カウンセリング
  -#       -#   %ul.dropdwn_menu
  -#       -#     %li
  -#       -#       %a{:href => "#"} D1
  -#       -#     %li
  -#       -#       %a{:href => "#"} D2
  -#       -#     %li
  -#       -#       %a{:href => "#"} D3
  -#       -#     %li
  -#       -#       %a{:href => "#"} D4
  -#       -#     %li
  -#       -#       %a{:href => "#"} D5

  -#       -# %li
  -#       -#   恋愛・結婚
  -#       -#   %ul.dropdwn_menu
  -#       -#     %li
  -#       -#       %a{:href => "#"} D1
  -#       -#     %li
  -#       -#       %a{:href => "#"} D2
  -#       -#     %li
  -#       -#       %a{:href => "#"} D3
  -#       -#     %li
  -#       -#       %a{:href => "#"} D4
  -#       -#     %li
  -#       -#       %a{:href => "#"} D5

  -#       -# %li
  -#       -#   美容・ファッション・健康
  -#       -#   %ul.dropdwn_menu
  -#       -#     %li
  -#       -#       %a{:href => "#"} D1
  -#       -#     %li
  -#       -#       %a{:href => "#"} D2
  -#       -#     %li
  -#       -#       %a{:href => "#"} D3
  -#       -#     %li
  -#       -#       %a{:href => "#"} D4
  -#       -#     %li
  -#       -#       %a{:href => "#"} D5

  -#       -# %li
  -#       -#   翻訳・語学
  -#       -#   %ul.dropdwn_menu
  -#       -#     %li
  -#       -#       %a{:href => "#"} D1
  -#       -#     %li
  -#       -#       %a{:href => "#"} D2
  -#       -#     %li
  -#       -#       %a{:href => "#"} D3
  -#       -#     %li
  -#       -#       %a{:href => "#"} D4
  -#       -#     %li
  -#       -#       %a{:href => "#"} D5
              

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title SkillShareMarket
    = favicon_link_tag('favicon.ico')
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %script{:src => "https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"}

  %body
    =render "/layouts/header"
    = yield
    =render "/layouts/footer"

app/views/layouts/devise.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title SkillShareMarket
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    =render "/devise/registrations/header"
    = yield
    =render "/layouts/footer"